### ISSUE TITLE
voxceleb dataset

### ISSUE THREAD

**Issue by yy835055664** [Wadaboa/titanet#5]
Hi, thank you so much for sharing this code.
Recently, I have been reproducing and learning your project. Regarding custom data sets, both data sets in your project use torchaudio's own data. I have tried custom data in the past few days, but there have been many problems, resulting in failure. Hope you can guide me on non-torchaudio data such as the voxceleb dataset. thank you very much!

**Comment by Wadaboa** [comment]
Hi there, 

as explained in issue #3 you just need to subclass `SpeakerDataset` and the data you use doesn't need to be from torchaudio. What you could do for voxceleb is download the dataset locally, understand how the data is organized (in terms of folder structure) and implement the abstract methods required by `SpeakerDataset`. 

Otherwise, you could wrap the dataset using some other library such as [this one](https://audtorch.readthedocs.io/en/0.1.1/api-datasets.html#voxceleb1). 

If you need more guidance, please be more specific with the "failures" you mentioned. 

Thanks,
Alessio.
